// Mocks generated by Mockito 5.4.6 from annotations
// in aedes_alert_yungrai/test/features/home/controllers/home_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:aedes_alert_yungrai/features/home/data/models/area_model.dart'
    as _i5;
import 'package:aedes_alert_yungrai/features/home/data/models/notification_model.dart'
    as _i8;
import 'package:aedes_alert_yungrai/features/home/domain/entities/weather_forecast_model.dart'
    as _i2;
import 'package:aedes_alert_yungrai/features/home/domain/use_cases/get_latest_area_for_district_use_case.dart'
    as _i10;
import 'package:aedes_alert_yungrai/features/home/domain/use_cases/get_latest_notification_use_case.dart'
    as _i7;
import 'package:aedes_alert_yungrai/features/home/domain/use_cases/get_nearest_area_use_case.dart'
    as _i3;
import 'package:aedes_alert_yungrai/features/home/domain/use_cases/get_weather_forecast_use_case.dart'
    as _i9;
import 'package:cloud_firestore/cloud_firestore.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeWeatherForecastModel_0 extends _i1.SmartFake
    implements _i2.WeatherForecastModel {
  _FakeWeatherForecastModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetNearestAreaUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetNearestAreaUseCase extends _i1.Mock
    implements _i3.GetNearestAreaUseCase {
  MockGetNearestAreaUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.AreaModel?> execute(
    _i6.GeoPoint? userLocation, {
    double? radiusKm = 5.0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [userLocation], {#radiusKm: radiusKm}),
            returnValue: _i4.Future<_i5.AreaModel?>.value(),
          )
          as _i4.Future<_i5.AreaModel?>);
}

/// A class which mocks [GetLatestNotificationUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetLatestNotificationUseCase extends _i1.Mock
    implements _i7.GetLatestNotificationUseCase {
  MockGetLatestNotificationUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i8.NotificationModel?> execute(String? areaId) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [areaId]),
            returnValue: _i4.Future<_i8.NotificationModel?>.value(),
          )
          as _i4.Future<_i8.NotificationModel?>);
}

/// A class which mocks [GetWeatherForecastUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetWeatherForecastUseCase extends _i1.Mock
    implements _i9.GetWeatherForecastUseCase {
  MockGetWeatherForecastUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.WeatherForecastModel> execute(_i6.GeoPoint? location) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [location]),
            returnValue: _i4.Future<_i2.WeatherForecastModel>.value(
              _FakeWeatherForecastModel_0(
                this,
                Invocation.method(#execute, [location]),
              ),
            ),
          )
          as _i4.Future<_i2.WeatherForecastModel>);
}

/// A class which mocks [GetLatestAreaForDistrictUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetLatestAreaForDistrictUseCase extends _i1.Mock
    implements _i10.GetLatestAreaForDistrictUseCase {
  MockGetLatestAreaForDistrictUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i5.AreaModel?> execute(String? district) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [district]),
            returnValue: _i4.Future<_i5.AreaModel?>.value(),
          )
          as _i4.Future<_i5.AreaModel?>);
}
