// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5g-LZxVOtmwtCUBpqp7zbEVJYtl2M95I',
    appId: '1:718444697672:web:63829b28ab03a29428e07d',
    messagingSenderId: '718444697672',
    projectId: 'yungrai-aedesalert',
    authDomain: 'yungrai-aedesalert.firebaseapp.com',
    storageBucket: 'yungrai-aedesalert.firebasestorage.app',
    measurementId: 'G-YTJWSYB1CL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPNDrI0MvLQ64rXcpwyOiIhwsV04IUyJU',
    appId: '1:718444697672:android:680f95c4f1a478f428e07d',
    messagingSenderId: '718444697672',
    projectId: 'yungrai-aedesalert',
    storageBucket: 'yungrai-aedesalert.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmgrB_fbxOL6gTIzSAeLVlz7L1v1igDZk',
    appId: '1:718444697672:ios:ef6c2457c31d136d28e07d',
    messagingSenderId: '718444697672',
    projectId: 'yungrai-aedesalert',
    storageBucket: 'yungrai-aedesalert.firebasestorage.app',
    iosBundleId: 'com.example.aedesAlertYungrai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmgrB_fbxOL6gTIzSAeLVlz7L1v1igDZk',
    appId: '1:718444697672:ios:ef6c2457c31d136d28e07d',
    messagingSenderId: '718444697672',
    projectId: 'yungrai-aedesalert',
    storageBucket: 'yungrai-aedesalert.firebasestorage.app',
    iosBundleId: 'com.example.aedesAlertYungrai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5g-LZxVOtmwtCUBpqp7zbEVJYtl2M95I',
    appId: '1:718444697672:web:c8bfff08f21a713628e07d',
    messagingSenderId: '718444697672',
    projectId: 'yungrai-aedesalert',
    authDomain: 'yungrai-aedesalert.firebaseapp.com',
    storageBucket: 'yungrai-aedesalert.firebasestorage.app',
    measurementId: 'G-Q3SNJQDE07',
  );
}
