// Mocks generated by Mockito 5.4.6 from annotations
// in aedes_alert_yungrai/test/features/dashboard/controllers/dashboard_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:aedes_alert_yungrai/features/dashboard/domain/entities/dashboard_summary_model.dart'
    as _i6;
import 'package:aedes_alert_yungrai/features/dashboard/domain/use_cases/get_average_risk_score_use_case.dart'
    as _i3;
import 'package:aedes_alert_yungrai/features/dashboard/domain/use_cases/get_dashboard_summary_use_case.dart'
    as _i7;
import 'package:aedes_alert_yungrai/features/dashboard/domain/use_cases/get_monthly_trend_use_case.dart'
    as _i4;
import 'package:aedes_alert_yungrai/features/dashboard/domain/use_cases/get_risk_counts_use_case.dart'
    as _i2;
import 'package:aedes_alert_yungrai/features/dashboard/domain/use_cases/get_top_areas_use_case.dart'
    as _i5;
import 'package:cloud_firestore/cloud_firestore.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeGetRiskCountsUseCase_0 extends _i1.SmartFake
    implements _i2.GetRiskCountsUseCase {
  _FakeGetRiskCountsUseCase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetAverageRiskScoreUseCase_1 extends _i1.SmartFake
    implements _i3.GetAverageRiskScoreUseCase {
  _FakeGetAverageRiskScoreUseCase_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetMonthlyTrendUseCase_2 extends _i1.SmartFake
    implements _i4.GetMonthlyTrendUseCase {
  _FakeGetMonthlyTrendUseCase_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGetTopAreasUseCase_3 extends _i1.SmartFake
    implements _i5.GetTopAreasUseCase {
  _FakeGetTopAreasUseCase_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDashboardSummaryModel_4 extends _i1.SmartFake
    implements _i6.DashboardSummaryModel {
  _FakeDashboardSummaryModel_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetDashboardSummaryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetDashboardSummaryUseCase extends _i1.Mock
    implements _i7.GetDashboardSummaryUseCase {
  MockGetDashboardSummaryUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetRiskCountsUseCase get getRiskCounts =>
      (super.noSuchMethod(
            Invocation.getter(#getRiskCounts),
            returnValue: _FakeGetRiskCountsUseCase_0(
              this,
              Invocation.getter(#getRiskCounts),
            ),
          )
          as _i2.GetRiskCountsUseCase);

  @override
  _i3.GetAverageRiskScoreUseCase get getAverageScore =>
      (super.noSuchMethod(
            Invocation.getter(#getAverageScore),
            returnValue: _FakeGetAverageRiskScoreUseCase_1(
              this,
              Invocation.getter(#getAverageScore),
            ),
          )
          as _i3.GetAverageRiskScoreUseCase);

  @override
  _i4.GetMonthlyTrendUseCase get getMonthlyTrend =>
      (super.noSuchMethod(
            Invocation.getter(#getMonthlyTrend),
            returnValue: _FakeGetMonthlyTrendUseCase_2(
              this,
              Invocation.getter(#getMonthlyTrend),
            ),
          )
          as _i4.GetMonthlyTrendUseCase);

  @override
  _i5.GetTopAreasUseCase get getTopAreas =>
      (super.noSuchMethod(
            Invocation.getter(#getTopAreas),
            returnValue: _FakeGetTopAreasUseCase_3(
              this,
              Invocation.getter(#getTopAreas),
            ),
          )
          as _i5.GetTopAreasUseCase);

  @override
  _i8.Future<_i6.DashboardSummaryModel> execute({
    _i9.GeoPoint? userLocation,
    String? userDistrict,
    String? selectedMonthKey,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [], {
              #userLocation: userLocation,
              #userDistrict: userDistrict,
              #selectedMonthKey: selectedMonthKey,
            }),
            returnValue: _i8.Future<_i6.DashboardSummaryModel>.value(
              _FakeDashboardSummaryModel_4(
                this,
                Invocation.method(#execute, [], {
                  #userLocation: userLocation,
                  #userDistrict: userDistrict,
                  #selectedMonthKey: selectedMonthKey,
                }),
              ),
            ),
          )
          as _i8.Future<_i6.DashboardSummaryModel>);
}
