// Mocks generated by Mockito 5.4.6 from annotations
// in aedes_alert_yungrai/test/features/dashboard/services/get_dashboard_summary_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:aedes_alert_yungrai/features/dashboard/models/monthly_risk_data_model.dart'
    as _i7;
import 'package:aedes_alert_yungrai/features/dashboard/models/risk_count_model.dart'
    as _i2;
import 'package:aedes_alert_yungrai/features/dashboard/services/get_average_risk_score_use_case.dart'
    as _i5;
import 'package:aedes_alert_yungrai/features/dashboard/services/get_monthly_trend_use_case.dart'
    as _i6;
import 'package:aedes_alert_yungrai/features/dashboard/services/get_risk_counts_use_case.dart'
    as _i3;
import 'package:aedes_alert_yungrai/features/dashboard/services/get_top_areas_use_case.dart'
    as _i8;
import 'package:aedes_alert_yungrai/features/home/models/area_model.dart'
    as _i9;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRiskCountModel_0 extends _i1.SmartFake
    implements _i2.RiskCountModel {
  _FakeRiskCountModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetRiskCountsUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetRiskCountsUseCase extends _i1.Mock
    implements _i3.GetRiskCountsUseCase {
  MockGetRiskCountsUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.RiskCountModel> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue: _i4.Future<_i2.RiskCountModel>.value(
              _FakeRiskCountModel_0(this, Invocation.method(#execute, [])),
            ),
          )
          as _i4.Future<_i2.RiskCountModel>);
}

/// A class which mocks [GetAverageRiskScoreUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAverageRiskScoreUseCase extends _i1.Mock
    implements _i5.GetAverageRiskScoreUseCase {
  MockGetAverageRiskScoreUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<double> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue: _i4.Future<double>.value(0.0),
          )
          as _i4.Future<double>);
}

/// A class which mocks [GetMonthlyTrendUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetMonthlyTrendUseCase extends _i1.Mock
    implements _i6.GetMonthlyTrendUseCase {
  MockGetMonthlyTrendUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i7.MonthlyRiskDataModel>> execute() =>
      (super.noSuchMethod(
            Invocation.method(#execute, []),
            returnValue: _i4.Future<List<_i7.MonthlyRiskDataModel>>.value(
              <_i7.MonthlyRiskDataModel>[],
            ),
          )
          as _i4.Future<List<_i7.MonthlyRiskDataModel>>);
}

/// A class which mocks [GetTopAreasUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTopAreasUseCase extends _i1.Mock
    implements _i8.GetTopAreasUseCase {
  MockGetTopAreasUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i9.AreaModel>> execute({int? limit = 5}) =>
      (super.noSuchMethod(
            Invocation.method(#execute, [], {#limit: limit}),
            returnValue: _i4.Future<List<_i9.AreaModel>>.value(
              <_i9.AreaModel>[],
            ),
          )
          as _i4.Future<List<_i9.AreaModel>>);
}
